### ISSUE TITLE
Bug: For some examples, model.Run() returns true when false is expected

### ISSUE THREAD

**Issue by ejmahler** [mxgmn/WaveFunctionCollapse#14] opened 2016-10-01 21:13 UTC
WaveFunctionCollapse version tested: commit 333f592 (HEAD as of this writing)

In Main.cs, on line 40, we check to see if the model has found a solution with the given seed. If it has found a solution, we then save a bmp file of the solution. Thus, the expectation is that any bmp file saved via this program should be completely "collapsed".

For some examples, this is not the case, and bmp files are saved that are partially still in a "superposition" state. The only reason I can see for this is that model.run() is sometimes returning true even if it hasn't found a solution.

To reproduce this bug, delete every entry of samples.xml except one:
```
<samples>
	<simpletiled name="Summer" width="15" height="15" periodic="False" limit="15"/>
</samples>
```

And change line 38 of Main.cs from
`int seed = random.Next();`
to
`int seed = 474849158;`

Then run the program.

I expect to see one of two things: "CONTRADICTION" printed in the console with no bmp file created, or "DONE" printed in the console with a fully-collapsed BMP file created.

Instead, "DONE" is printed and a partially-resolved BMP file is created.

**Comment by ejmahler** [comment] 2016-10-01 21:25
The same bug occurs with samples.xml
```
<samples>
	<overlapping name="Village" N="3" symmetry="2" limit="50" periodic="True"/>
</samples>
```

And seed
`int seed = 362313200;`

This means that the bug occurs with both the overlapping model and the simple tiled model.

**Comment by kchapelier** [comment] 2016-10-01 21:45
I think this is the intended behavior with the `limit` property : it actually limits the number of iterations the generation is allowed to do. If the number of iterations reaches this limit without hitting a `contradiction` condition, the generation is considered a success.

**Comment by ejmahler** [comment] 2016-10-01 21:53
As I read the source of Run(), you're clearly correct.

But that doesn't seem intuitive to me -- even when providing an iteration limit, the main thing I want to know is whether or not the model now has a usable result. How would I know whether the result was complete or not? So IMO the bug still stands: I expect a return of true when the generation has completed successfully, and false otherwise.

This seems like a case of trying to cram a piece of information with three states (Complete, incomplete, impossible) into a variable with two states.

**Comment by kchapelier** [comment] 2016-10-01 22:03
I see that the samples.xml in the repo actually have those `limit` set. I wrongly assumed you added them. The `limit` properties should probably be removed from the file as they seems to be debug helpers more than anything.

**Comment by ejmahler** [comment] 2016-10-01 22:08
I edited the issue to indicate that that entry came from the existing samples.xml

**Comment by mxgmn** [comment] 2016-10-02 00:35
I included samples with the `limit` param in `samples.xml` to show how to generate partially completed results. Because they can be pretty, like the "Circles" one linked from README.

**Comment by mxgmn** [comment] 2016-10-03 14:10
@ejmahler @kchapelier Note sure if people get notifications if I don't mention their username. It seems that everybody understood each other here, closing.

**Closed by mxgmn** 2016-10-03 14:10 UTC
